## Packages

In [1]:
search_packages = [
    "openmmtools"
]

# Monthly downloads

## conda-forge downloads

In [12]:
# pdbinf =  1769
# kartograf =  1771

In [4]:
# Get historical conda-forge downloads
# This usually lags by two months so we don't have to worry about
# incomplete months

condadf = overall(
    search_packages,
    data_source='conda-forge',
    monthly=True
)
condadf

pkg_name     time
openmmtools  2021-01     921
             2021-02    4041
             2021-03    4551
             2021-04    3921
             2021-05    4693
             2021-06    5800
             2021-07    6588
             2021-08    7810
             2021-09    5580
             2021-10    6905
             2021-11    6391
             2021-12    4288
             2022-01    3545
             2022-02    3598
             2022-03    5032
             2022-04    5938
             2022-05    5385
             2022-06    5735
             2022-07    5450
             2022-08    5863
             2022-09    5775
             2022-10    5394
             2022-11    6124
             2022-12    4776
             2023-01    4927
             2023-02    8061
             2023-03    8161
             2023-04    4523
             2023-05    1641
             2023-06    1305
             2023-07     761
             2023-08     433
             2023-09     402
             2023-10     689
Name: counts, dtype: int64

In [5]:
condadf

pkg_name     time
openmmtools  2021-01     921
             2021-02    4041
             2021-03    4551
             2021-04    3921
             2021-05    4693
             2021-06    5800
             2021-07    6588
             2021-08    7810
             2021-09    5580
             2021-10    6905
             2021-11    6391
             2021-12    4288
             2022-01    3545
             2022-02    3598
             2022-03    5032
             2022-04    5938
             2022-05    5385
             2022-06    5735
             2022-07    5450
             2022-08    5863
             2022-09    5775
             2022-10    5394
             2022-11    6124
             2022-12    4776
             2023-01    4927
             2023-02    8061
             2023-03    8161
             2023-04    4523
             2023-05    1641
             2023-06    1305
             2023-07     761
             2023-08     433
             2023-09     402
             2023-10     689
Name: counts, dtype: int64

In [6]:
df = pd.DataFrame(condadf).reset_index()

In [7]:
allowed_months = [f"2023-{x:02d}" for x in range(6, 12)]
past_five_months = df[df.time.isin(allowed_months)]

In [8]:
past_five_months

       pkg_name     time  counts
29  openmmtools  2023-06    1305
30  openmmtools  2023-07     761
31  openmmtools  2023-08     433
32  openmmtools  2023-09     402
33  openmmtools  2023-10     689

In [9]:
average = (past_five_months.counts.sum() / len(past_five_months.time.unique()))
average

718.0

## Pypi Stats

In [21]:
help(pypistats.overall)

Help on function overall in module pypistats:

overall(package: 'str', mirrors: 'bool | str | None' = None, **kwargs: 'str')
    Retrieve the aggregate daily download time series with or without mirror
    downloads

In [36]:
# PyPI doesn't store a lot of historical data, so we get the last 3 months

pypi_packages = [
    "openfe",
    "gufe",
    "kartograf",
    "cinnabar",
    "pdbinf",
    "exorcist"
]

pypi_dfs = []

for package in pypi_packages:
    df_ = pypistats.overall(
        package, total=True,
       mirrors=True, format="pandas",
       start_date='2022-11-01',
       end_date='2023-10-31'
    )
    df_["Package"] = package
    pypi_dfs.append(df_)

pypidf = pd.concat(pypi_dfs)

/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_88610/2376607087.py:15: UserWarning: Requested start date (2022-11-01) is before earliest available data (2023-06-07), because data is only available for 180 days. See https://pypistats.org/about#data
  df_ = pypistats.overall(
/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_88610/2376607087.py:15: UserWarning: Requested start date (2022-11-01) is before earliest available data (2023-06-07), because data is only available for 180 days. See https://pypistats.org/about#data
  df_ = pypistats.overall(
/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_88610/2376607087.py:15: UserWarning: Requested start date (2022-11-01) is before earliest available data (2023-06-07), because data is only available for 180 days. See https://pypistats.org/about#data
  df_ = pypistats.overall(
/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_88610/2376607087.py:15: UserWarning: Requested start date (2022-11-01) is before earliest available data (2023-06-07), because data is only available for 180 days. See https://pypistats.org/about#data
  df_ = pypistats.overall(
/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_88610/2376607087.py:15: UserWarning: Requested start date (2022-11-01) is before earliest available data (2023-06-08), because data is only available for 180 days. See https://pypistats.org/about#data
  df_ = pypistats.overall(
/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_88610/2376607087.py:15: UserWarning: Requested start date (2022-11-01) is before earliest available data (2023-06-07), because data is only available for 180 days. See https://pypistats.org/about#data
  df_ = pypistats.overall(

In [48]:
sorted([x for x in pypidf.date.unique() if isinstance(x, str)])

['2023-06-07',
 '2023-06-08',
 '2023-06-09',
 '2023-06-10',
 '2023-06-11',
 '2023-06-12',
 '2023-06-13',
 '2023-06-14',
 '2023-06-15',
 '2023-06-16',
 '2023-06-17',
 '2023-06-18',
 '2023-06-19',
 '2023-06-20',
 '2023-06-21',
 '2023-06-22',
 '2023-06-23',
 '2023-06-24',
 '2023-06-25',
 '2023-06-26',
 '2023-06-27',
 '2023-06-28',
 '2023-06-29',
 '2023-06-30',
 '2023-07-01',
 '2023-07-02',
 '2023-07-03',
 '2023-07-04',
 '2023-07-05',
 '2023-07-06',
 '2023-07-07',
 '2023-07-08',
 '2023-07-09',
 '2023-07-10',
 '2023-07-11',
 '2023-07-12',
 '2023-07-13',
 '2023-07-14',
 '2023-07-15',
 '2023-07-16',
 '2023-07-17',
 '2023-07-18',
 '2023-07-19',
 '2023-07-20',
 '2023-07-21',
 '2023-07-22',
 '2023-07-23',
 '2023-07-24',
 '2023-07-25',
 '2023-07-26',
 '2023-07-27',
 '2023-07-28',
 '2023-07-29',
 '2023-07-30',
 '2023-07-31',
 '2023-08-01',
 '2023-08-02',
 '2023-08-03',
 '2023-08-04',
 '2023-08-05',
 '2023-08-06',
 '2023-08-07',
 '2023-08-08',
 '2023-08-09',
 '2023-08-10',
 '2023-08-11',
 '2023-08-12',
 '2023-08-13',
 '2023-08-14',
 '2023-08-15',
 '2023-08-16',
 '2023-08-17',
 '2023-08-18',
 '2023-08-19',
 '2023-08-20',
 '2023-08-21',
 '2023-08-22',
 '2023-08-23',
 '2023-08-24',
 '2023-08-25',
 '2023-08-26',
 '2023-08-27',
 '2023-08-28',
 '2023-08-29',
 '2023-08-30',
 '2023-08-31',
 '2023-09-01',
 '2023-09-02',
 '2023-09-03',
 '2023-09-04',
 '2023-09-05',
 '2023-09-06',
 '2023-09-07',
 '2023-09-08',
 '2023-09-09',
 '2023-09-10',
 '2023-09-11',
 '2023-09-12',
 '2023-09-13',
 '2023-09-14',
 '2023-09-15',
 '2023-09-16',
 '2023-09-17',
 '2023-09-18',
 '2023-09-19',
 '2023-09-20',
 '2023-09-21',
 '2023-09-22',
 '2023-09-23',
 '2023-09-24',
 '2023-09-25',
 '2023-09-26',
 '2023-09-27',
 '2023-09-28',
 '2023-09-29',
 '2023-09-30',
 '2023-10-01',
 '2023-10-02',
 '2023-10-03',
 '2023-10-04',
 '2023-10-05',
 '2023-10-06',
 '2023-10-07',
 '2023-10-08',
 '2023-10-09',
 '2023-10-10',
 '2023-10-11',
 '2023-10-12',
 '2023-10-13',
 '2023-10-14',
 '2023-10-15',
 '2023-10-16',
 '2023-10-17',
 '2023-10-18',
 '2023-10-19',
 '2023-10-20',
 '2023-10-21',
 '2023-10-22',
 '2023-10-23',
 '2023-10-24',
 '2023-10-25',
 '2023-10-26',
 '2023-10-27',
 '2023-10-28',
 '2023-10-29',
 '2023-10-30',
 '2023-10-31']

In [37]:
pypidf.groupby("category").get_group("Total")

    category  date percent  downloads    Package
147    Total  None    None       4832     openfe
97     Total  None    None        308       gufe
127    Total  None    None       2005  kartograf
97     Total  None    None        376   cinnabar
99     Total  None    None        913     pdbinf
96     Total  None    None        302   exorcist

In [38]:
pypi_total = pypidf.groupby("category").get_group("Total").sum().downloads
pypi_total_downloads = int(pypi_total) / 5
print(pypidf)
print(pypi_total_downloads)

         category        date percent  downloads    Package
0    with_mirrors  2023-09-25   2.94%        142     openfe
1    with_mirrors  2023-07-18   2.59%        125     openfe
2    with_mirrors  2023-07-19   2.32%        112     openfe
3    with_mirrors  2023-08-03   1.90%         92     openfe
4    with_mirrors  2023-08-06   1.72%         83     openfe
5    with_mirrors  2023-06-18   1.68%         81     openfe
6    with_mirrors  2023-06-24   1.63%         79     openfe
7    with_mirrors  2023-08-28   1.61%         78     openfe
8    with_mirrors  2023-07-01   1.45%         70     openfe
9    with_mirrors  2023-08-16   1.43%         69     openfe
10   with_mirrors  2023-10-25   1.43%         69     openfe
11   with_mirrors  2023-06-07   1.41%         68     openfe
12   with_mirrors  2023-08-09   1.41%         68     openfe
13   with_mirrors  2023-09-26   1.41%         68     openfe
14   with_mirrors  2023-06-13   1.37%         66     openfe
15   with_mirrors  2023-08-15   1.35%         65     openfe
16   with_mirrors  2023-08-26   1.35%         65     openfe
17   with_mirrors  2023-08-12   1.24%         60     openfe
18   with_mirrors  2023-09-07   1.24%         60     openfe
19   with_mirrors  2023-10-30   1.24%         60     openfe
20   with_mirrors  2023-08-27   1.22%         59     openfe
21   with_mirrors  2023-06-17   1.20%         58     openfe
22   with_mirrors  2023-08-13   1.20%         58     openfe
23   with_mirrors  2023-08-01   1.12%         54     openfe
24   with_mirrors  2023-07-10   1.06%         51     openfe
25   with_mirrors  2023-07-12   0.99%         48     openfe
26   with_mirrors  2023-07-09   0.97%         47     openfe
27   with_mirrors  2023-09-30   0.95%         46     openfe
28   with_mirrors  2023-06-08   0.93%         45     openfe
29   with_mirrors  2023-06-28   0.93%         45     openfe
30   with_mirrors  2023-08-10   0.93%         45     openfe
31   with_mirrors  2023-08-14   0.91%         44     openfe
32   with_mirrors  2023-08-18   0.91%         44     openfe
33   with_mirrors  2023-07-05   0.89%         43     openfe
34   with_mirrors  2023-08-11   0.89%         43     openfe
35   with_mirrors  2023-07-15   0.85%         41     openfe
36   with_mirrors  2023-10-03   0.85%         41     openfe
37   with_mirrors  2023-10-04   0.85%         41     openfe
38   with_mirrors  2023-06-14   0.83%         40     openfe
39   with_mirrors  2023-08-19   0.83%         40     openfe
40   with_mirrors  2023-06-26   0.81%         39     openfe
41   with_mirrors  2023-07-22   0.81%         39     openfe
42   with_mirrors  2023-07-27   0.81%         39     openfe
43   with_mirrors  2023-08-17   0.81%         39     openfe
44   with_mirrors  2023-09-15   0.81%         39     openfe
45   with_mirrors  2023-06-21   0.79%         38     openfe
46   with_mirrors  2023-06-30   0.79%         38     openfe
47   with_mirrors  2023-08-04   0.79%         38     openfe
48   with_mirrors  2023-07-07   0.77%         37     openfe
49   with_mirrors  2023-06-27   0.75%         36     openfe
50   with_mirrors  2023-10-07   0.75%         36     openfe
51   with_mirrors  2023-08-02   0.72%         35     openfe
52   with_mirrors  2023-09-02   0.72%         35     openfe
53   with_mirrors  2023-06-29   0.70%         34     openfe
54   with_mirrors  2023-07-11   0.70%         34     openfe
55   with_mirrors  2023-07-25   0.70%         34     openfe
56   with_mirrors  2023-09-19   0.68%         33     openfe
57   with_mirrors  2023-06-22   0.66%         32     openfe
58   with_mirrors  2023-07-03   0.66%         32     openfe
59   with_mirrors  2023-09-11   0.66%         32     openfe
60   with_mirrors  2023-10-15   0.66%         32     openfe
61   with_mirrors  2023-06-16   0.64%         31     openfe
62   with_mirrors  2023-10-12   0.64%         31     openfe
63   with_mirrors  2023-08-24   0.62%         30     openfe
64   with_mirrors  2023-09-06   0.62%         30     openfe
65   with_mirrors  2023-10-22   0.62%         30     openfe
66   with_mirrors  2023-10-31   0.62%         30     openfe
67   with_mirrors  2023-06-20   0.60%         29     openfe
68   with_mirrors  2023-09-08   0.58%         28     openfe
69   with_mirrors  2023-07-14   0.56%         27     openfe
70   with_mirrors  2023-09-28   0.56%         27     openfe
71   with_mirrors  2023-10-08   0.56%         27     openfe
72   with_mirrors  2023-10-14   0.56%         27     openfe
73   with_mirrors  2023-10-16   0.56%         27     openfe
74   with_mirrors  2023-06-12   0.54%         26     openfe
75   with_mirrors  2023-09-10   0.54%         26     openfe
76   with_mirrors  2023-10-10   0.54%         26     openfe
77   with_mirrors  2023-10-17   0.52%         25     openfe
78   with_mirrors  2023-07-02   0.50%         24     openfe
79   with_mirrors  2023-07-13   0.50%         24     openfe
80   with_mirrors  2023-07-21   0.50%         24     openfe
81   with_mirrors  2023-07-29   0.48%         23     openfe
82   with_mirrors  2023-09-23   0.48%         23     openfe
83   with_mirrors  2023-06-15   0.46%         22     openfe
84   with_mirrors  2023-06-19   0.46%         22     openfe
85   with_mirrors  2023-07-20   0.46%         22     openfe
86   with_mirrors  2023-08-30   0.46%         22     openfe
87   with_mirrors  2023-09-12   0.46%         22     openfe
88   with_mirrors  2023-09-20   0.46%         22     openfe
89   with_mirrors  2023-09-22   0.46%         22     openfe
90   with_mirrors  2023-10-28   0.46%         22     openfe
91   with_mirrors  2023-07-16   0.43%         21     openfe
92   with_mirrors  2023-08-29   0.43%         21     openfe
93   with_mirrors  2023-10-18   0.41%         20     openfe
94   with_mirrors  2023-07-08   0.39%         19     openfe
95   with_mirrors  2023-07-31   0.39%         19     openfe
96   with_mirrors  2023-08-08   0.39%         19     openfe
97   with_mirrors  2023-08-31   0.39%         19     openfe
98   with_mirrors  2023-09-01   0.39%         19     openfe
99   with_mirrors  2023-10-11   0.39%         19     openfe
100  with_mirrors  2023-10-20   0.39%         19     openfe
101  with_mirrors  2023-10-24   0.39%         19     openfe
102  with_mirrors  2023-10-27   0.39%         19     openfe
103  with_mirrors  2023-06-11   0.37%         18     openfe
104  with_mirrors  2023-07-28   0.37%         18     openfe
105  with_mirrors  2023-08-05   0.37%         18     openfe
106  with_mirrors  2023-08-21   0.37%         18     openfe
107  with_mirrors  2023-08-23   0.37%         18     openfe
108  with_mirrors  2023-09-18   0.37%         18     openfe
109  with_mirrors  2023-10-29   0.35%         17     openfe
110  with_mirrors  2023-07-26   0.33%         16     openfe
111  with_mirrors  2023-07-30   0.33%         16     openfe
112  with_mirrors  2023-09-04   0.33%         16     openfe
113  with_mirrors  2023-09-13   0.33%         16     openfe
114  with_mirrors  2023-09-16   0.33%         16     openfe
115  with_mirrors  2023-09-27   0.33%         16     openfe
116  with_mirrors  2023-10-13   0.33%         16     openfe
117  with_mirrors  2023-10-26   0.33%         16     openfe
118  with_mirrors  2023-09-09   0.31%         15     openfe
119  with_mirrors  2023-06-10   0.29%         14     openfe
120  with_mirrors  2023-08-07   0.29%         14     openfe
121  with_mirrors  2023-09-24   0.29%         14     openfe
122  with_mirrors  2023-10-09   0.29%         14     openfe
123  with_mirrors  2023-06-23   0.27%         13     openfe
124  with_mirrors  2023-07-17   0.27%         13     openfe
125  with_mirrors  2023-07-24   0.27%         13     openfe
126  with_mirrors  2023-09-05   0.27%         13     openfe
127  with_mirrors  2023-06-25   0.25%         12     openfe
128  with_mirrors  2023-07-06   0.25%         12     openfe
129  with_mirrors  2023-08-20   0.25%         12     openfe
130  with_mirrors  2023-09-21   0.25%         12     openfe
131  with_mirrors  2023-10-19   0.25%         12     openfe
132  with_mirrors  2023-09-14   0.23%         11     openfe
133  with_mirrors  2023-10-06   0.23%         11     openfe
134  with_mirrors  2023-10-02   0.21%         10     openfe
135  with_mirrors  2023-06-09   0.19%          9     openfe
136  with_mirrors  2023-07-04   0.19%          9     openfe
137  with_mirrors  2023-08-22   0.19%          9     openfe
138  with_mirrors  2023-09-03   0.19%          9     openfe
139  with_mirrors  2023-09-29   0.19%          9     openfe
140  with_mirrors  2023-10-01   0.19%          9     openfe
141  with_mirrors  2023-08-25   0.17%          8     openfe
142  with_mirrors  2023-10-05   0.17%          8     openfe
143  with_mirrors  2023-07-23   0.14%          7     openfe
144  with_mirrors  2023-10-23   0.14%          7     openfe
145  with_mirrors  2023-09-17   0.12%          6     openfe
146  with_mirrors  2023-10-21   0.12%          6     openfe
147         Total        None    None       4832     openfe
0    with_mirrors  2023-08-25   3.90%         12       gufe
1    with_mirrors  2023-09-23   3.25%         10       gufe
2    with_mirrors  2023-07-31   2.92%          9       gufe
3    with_mirrors  2023-06-11   2.27%          7       gufe
4    with_mirrors  2023-08-08   2.27%          7       gufe
5    with_mirrors  2023-06-08   1.95%          6       gufe
6    with_mirrors  2023-06-26   1.95%          6       gufe
7    with_mirrors  2023-06-27   1.95%          6       gufe
8    with_mirrors  2023-07-07   1.95%          6       gufe
9    with_mirrors  2023-08-10   1.95%          6       gufe
10   with_mirrors  2023-06-16   1.62%          5       gufe
11   with_mirrors  2023-06-21   1.62%          5       gufe
12   with_mirrors  2023-07-30   1.62%          5       gufe
13   with_mirrors  2023-08-12   1.62%          5       gufe
14   with_mirrors  2023-09-25   1.62%          5       gufe
15   with_mirrors  2023-10-08   1.62%          5       gufe
16   with_mirrors  2023-10-21   1.62%          5       gufe
17   with_mirrors  2023-10-28   1.62%          5       gufe
18   with_mirrors  2023-06-22   1.30%          4       gufe
19   with_mirrors  2023-06-23   1.30%          4       gufe
20   with_mirrors  2023-07-04   1.30%          4       gufe
21   with_mirrors  2023-07-09   1.30%          4       gufe
22   with_mirrors  2023-07-12   1.30%          4       gufe
23   with_mirrors  2023-07-13   1.30%          4       gufe
24   with_mirrors  2023-07-15   1.30%          4       gufe
25   with_mirrors  2023-07-26   1.30%          4       gufe
26   with_mirrors  2023-08-01   1.30%          4       gufe
27   with_mirrors  2023-08-05   1.30%          4       gufe
28   with_mirrors  2023-08-09   1.30%          4       gufe
29   with_mirrors  2023-08-13   1.30%          4       gufe
30   with_mirrors  2023-09-01   1.30%          4       gufe
31   with_mirrors  2023-09-04   1.30%          4       gufe
32   with_mirrors  2023-09-14   1.30%          4       gufe
33   with_mirrors  2023-09-15   1.30%          4       gufe
34   with_mirrors  2023-09-29   1.30%          4       gufe
35   with_mirrors  2023-10-26   1.30%          4       gufe
36   with_mirrors  2023-10-31   1.30%          4       gufe
37   with_mirrors  2023-06-12   0.97%          3       gufe
38   with_mirrors  2023-07-23   0.97%          3       gufe
39   with_mirrors  2023-07-24   0.97%          3       gufe
40   with_mirrors  2023-08-06   0.97%          3       gufe
41   with_mirrors  2023-08-11   0.97%          3       gufe
42   with_mirrors  2023-08-23   0.97%          3       gufe
43   with_mirrors  2023-09-11   0.97%          3       gufe
44   with_mirrors  2023-09-22   0.97%          3       gufe
45   with_mirrors  2023-10-24   0.97%          3       gufe
46   with_mirrors  2023-10-30   0.97%          3       gufe
47   with_mirrors  2023-06-07   0.65%          2       gufe
48   with_mirrors  2023-06-13   0.65%          2       gufe
49   with_mirrors  2023-06-19   0.65%          2       gufe
50   with_mirrors  2023-06-24   0.65%          2       gufe
51   with_mirrors  2023-06-28   0.65%          2       gufe
52   with_mirrors  2023-06-30   0.65%          2       gufe
53   with_mirrors  2023-07-02   0.65%          2       gufe
54   with_mirrors  2023-07-03   0.65%          2       gufe
55   with_mirrors  2023-07-08   0.65%          2       gufe
56   with_mirrors  2023-07-11   0.65%          2       gufe
57   with_mirrors  2023-07-16   0.65%          2       gufe
58   with_mirrors  2023-07-17   0.65%          2       gufe
59   with_mirrors  2023-07-27   0.65%          2       gufe
60   with_mirrors  2023-07-29   0.65%          2       gufe
61   with_mirrors  2023-08-02   0.65%          2       gufe
62   with_mirrors  2023-08-04   0.65%          2       gufe
63   with_mirrors  2023-08-14   0.65%          2       gufe
64   with_mirrors  2023-08-15   0.65%          2       gufe
65   with_mirrors  2023-08-18   0.65%          2       gufe
66   with_mirrors  2023-08-29   0.65%          2       gufe
67   with_mirrors  2023-08-30   0.65%          2       gufe
68   with_mirrors  2023-09-05   0.65%          2       gufe
69   with_mirrors  2023-09-09   0.65%          2       gufe
70   with_mirrors  2023-09-10   0.65%          2       gufe
71   with_mirrors  2023-09-20   0.65%          2       gufe
72   with_mirrors  2023-09-24   0.65%          2       gufe
73   with_mirrors  2023-09-27   0.65%          2       gufe
74   with_mirrors  2023-10-02   0.65%          2       gufe
75   with_mirrors  2023-10-03   0.65%          2       gufe
76   with_mirrors  2023-10-04   0.65%          2       gufe
77   with_mirrors  2023-10-07   0.65%          2       gufe
78   with_mirrors  2023-10-11   0.65%          2       gufe
79   with_mirrors  2023-10-13   0.65%          2       gufe
80   with_mirrors  2023-10-18   0.65%          2       gufe
81   with_mirrors  2023-10-25   0.65%          2       gufe
82   with_mirrors  2023-10-27   0.65%          2       gufe
83   with_mirrors  2023-10-29   0.65%          2       gufe
84   with_mirrors  2023-06-09   0.32%          1       gufe
85   with_mirrors  2023-06-14   0.32%          1       gufe
86   with_mirrors  2023-06-15   0.32%          1       gufe
87   with_mirrors  2023-06-17   0.32%          1       gufe
88   with_mirrors  2023-06-18   0.32%          1       gufe
89   with_mirrors  2023-07-01   0.32%          1       gufe
90   with_mirrors  2023-07-18   0.32%          1       gufe
91   with_mirrors  2023-07-25   0.32%          1       gufe
92   with_mirrors  2023-08-27   0.32%          1       gufe
93   with_mirrors  2023-08-28   0.32%          1       gufe
94   with_mirrors  2023-08-31   0.32%          1       gufe
95   with_mirrors  2023-09-13   0.32%          1       gufe
96   with_mirrors  2023-09-18   0.32%          1       gufe
97          Total        None    None        308       gufe
0    with_mirrors  2023-08-08   7.98%        160  kartograf
1    with_mirrors  2023-08-09   4.69%         94  kartograf
2    with_mirrors  2023-06-07   3.79%         76  kartograf
3    with_mirrors  2023-06-08   3.39%         68  kartograf
4    with_mirrors  2023-08-10   2.99%         60  kartograf
5    with_mirrors  2023-08-26   2.64%         53  kartograf
6    with_mirrors  2023-09-24   2.39%         48  kartograf
7    with_mirrors  2023-08-25   2.24%         45  kartograf
8    with_mirrors  2023-07-17   2.09%         42  kartograf
9    with_mirrors  2023-10-30   1.80%         36  kartograf
10   with_mirrors  2023-09-23   1.65%         33  kartograf
11   with_mirrors  2023-06-23   1.60%         32  kartograf
12   with_mirrors  2023-07-24   1.50%         30  kartograf
13   with_mirrors  2023-08-01   1.40%         28  kartograf
14   with_mirrors  2023-08-11   1.40%         28  kartograf
15   with_mirrors  2023-08-12   1.40%         28  kartograf
16   with_mirrors  2023-08-13   1.40%         28  kartograf
17   with_mirrors  2023-06-12   1.35%         27  kartograf
18   with_mirrors  2023-10-28   1.35%         27  kartograf
19   with_mirrors  2023-08-14   1.30%         26  kartograf
20   with_mirrors  2023-06-11   1.25%         25  kartograf
21   with_mirrors  2023-06-14   1.25%         25  kartograf
22   with_mirrors  2023-07-08   1.20%         24  kartograf
23   with_mirrors  2023-07-13   1.20%         24  kartograf
24   with_mirrors  2023-10-03   1.20%         24  kartograf
25   with_mirrors  2023-07-10   1.10%         22  kartograf
26   with_mirrors  2023-09-06   1.05%         21  kartograf
27   with_mirrors  2023-06-28   1.00%         20  kartograf
28   with_mirrors  2023-08-02   1.00%         20  kartograf
29   with_mirrors  2023-09-05   1.00%         20  kartograf
30   with_mirrors  2023-09-13   1.00%         20  kartograf
31   with_mirrors  2023-09-15   1.00%         20  kartograf
32   with_mirrors  2023-06-09   0.95%         19  kartograf
33   with_mirrors  2023-06-20   0.95%         19  kartograf
34   with_mirrors  2023-07-14   0.95%         19  kartograf
35   with_mirrors  2023-09-29   0.95%         19  kartograf
36   with_mirrors  2023-09-11   0.85%         17  kartograf
37   with_mirrors  2023-07-05   0.80%         16  kartograf
38   with_mirrors  2023-09-21   0.80%         16  kartograf
39   with_mirrors  2023-06-17   0.75%         15  kartograf
40   with_mirrors  2023-07-11   0.75%         15  kartograf
41   with_mirrors  2023-08-06   0.75%         15  kartograf
42   with_mirrors  2023-08-15   0.75%         15  kartograf
43   with_mirrors  2023-07-04   0.70%         14  kartograf
44   with_mirrors  2023-08-30   0.70%         14  kartograf
45   with_mirrors  2023-09-12   0.70%         14  kartograf
46   with_mirrors  2023-09-27   0.70%         14  kartograf
47   with_mirrors  2023-10-09   0.70%         14  kartograf
48   with_mirrors  2023-10-21   0.70%         14  kartograf
49   with_mirrors  2023-10-29   0.70%         14  kartograf
50   with_mirrors  2023-06-19   0.65%         13  kartograf
51   with_mirrors  2023-08-05   0.65%         13  kartograf
52   with_mirrors  2023-09-26   0.65%         13  kartograf
53   with_mirrors  2023-09-28   0.65%         13  kartograf
54   with_mirrors  2023-06-10   0.60%         12  kartograf
55   with_mirrors  2023-07-02   0.60%         12  kartograf
56   with_mirrors  2023-08-17   0.60%         12  kartograf
57   with_mirrors  2023-08-20   0.60%         12  kartograf
58   with_mirrors  2023-08-22   0.60%         12  kartograf
59   with_mirrors  2023-08-31   0.60%         12  kartograf
60   with_mirrors  2023-09-03   0.60%         12  kartograf
61   with_mirrors  2023-09-04   0.60%         12  kartograf
62   with_mirrors  2023-09-10   0.60%         12  kartograf
63   with_mirrors  2023-10-06   0.60%         12  kartograf
64   with_mirrors  2023-10-07   0.60%         12  kartograf
65   with_mirrors  2023-10-12   0.60%         12  kartograf
66   with_mirrors  2023-10-27   0.60%         12  kartograf
67   with_mirrors  2023-10-31   0.60%         12  kartograf
68   with_mirrors  2023-06-24   0.55%         11  kartograf
69   with_mirrors  2023-06-26   0.55%         11  kartograf
70   with_mirrors  2023-07-01   0.55%         11  kartograf
71   with_mirrors  2023-07-09   0.55%         11  kartograf
72   with_mirrors  2023-10-20   0.55%         11  kartograf
73   with_mirrors  2023-08-07   0.50%         10  kartograf
74   with_mirrors  2023-08-23   0.50%         10  kartograf
75   with_mirrors  2023-07-03   0.45%          9  kartograf
76   with_mirrors  2023-07-25   0.45%          9  kartograf
77   with_mirrors  2023-07-28   0.45%          9  kartograf
78   with_mirrors  2023-10-18   0.45%          9  kartograf
79   with_mirrors  2023-09-14   0.40%          8  kartograf
80   with_mirrors  2023-07-06   0.35%          7  kartograf
81   with_mirrors  2023-10-11   0.35%          7  kartograf
82   with_mirrors  2023-06-18   0.30%          6  kartograf
83   with_mirrors  2023-06-27   0.30%          6  kartograf
84   with_mirrors  2023-08-19   0.30%          6  kartograf
85   with_mirrors  2023-09-09   0.30%          6  kartograf

In [45]:
pypi_total_downloads + average

1912.6000000000001

# Dependants

## conda-forge dependants

In [2]:
import tqdm
import subprocess

dependants = set()
for package in tqdm.tqdm(["openmmtools"]):
    toggle = False
    proc = subprocess.run(
        f"mamba repoquery whoneeds {package} -c conda-forge --quiet",
        shell=True,
        capture_output=True,
        text=True,
    )
    for line in proc.stdout.split("\n"):
        if line.strip().startswith("Name"):
            toggle = True
            continue
        if toggle:
            fields = line.strip().split()
            if len(fields) > 1:
                dependants.add(fields[0])

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.48s/it]

In [3]:
dependants

{'absolv',
 'absolv-base',
 'grand',
 'openfe',
 'openff-evaluator',
 'openff-evaluator-base',
 'perses',
 'ties_md',
 'transformato',
 'yank'}

In [33]:
len(non_openff_dependants)

17

## GitHub

In [13]:
openff_packages

{'openff-amber-ff-ports',
 'openff-bespokefit',
 'openff-evaluator',
 'openff-evaluator-base',
 'openff-forcefields',
 'openff-fragmenter',
 'openff-fragmenter-base',
 'openff-interchange',
 'openff-interchange-base',
 'openff-models',
 'openff-nagl',
 'openff-nagl-base',
 'openff-nagl-models',
 'openff-qcsubmit',
 'openff-recharge',
 'openff-toolkit',
 'openff-toolkit-base',
 'openff-toolkit-examples',
 'openff-units',
 'openff-utilities'}

In [15]:
import json

all_public_repos = set()
n_private_dependants = 0
for package in tqdm.tqdm(openff_packages):
    if package.endswith("-base"):
        proc = subprocess.run(
            f'github-dependents-info --repo openforcefield/{package} --sort name --json',
            capture_output=True,
            text=True,
            shell=True,
        )
        contents = json.loads(proc.stdout)
        public_repos = [
            x["name"]
            for x in contents["all_public_dependent_repos"]
        ]
        all_public_repos |= set(public_repos)
        n_private_dependants += contents["private_dependents_number"]

100%|███████████████████████████████████████████| 20/20 [00:04<00:00,  4.63it/s]

In [18]:
all_public_repos

set()

In [17]:
n_private_dependants

0

In [3]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from github import Github

%matplotlib inline

In [4]:
git = Github(os.environ['GH_API_TOKEN'])

In [5]:
org = "choderalab"

In [6]:
all_repos = [
    repo.name for repo in git.get_user(org).get_repos()
]

In [7]:
all_repos

['Abl_kinase_N368S',
 'alchemical-playground',
 'alchemy',
 'amberfb15',
 'ambermini',
 'antibody-mutations',
 'asapdiscovery',
 'asapdiscovery-mers-docking',
 'asapdiscovery-sars-retrospective',
 'assaytools',
 'assaytools2',
 'auditorium',
 'AurA-materials',
 'AURKA_UMN',
 'automatic-equilibration-detection',
 'automatic-state-decomposition',
 'autonomous-molecular-design',
 'bayesian-forcefields',
 'bayesian-free-energies',
 'bayesian-itc',
 'bbar',
 'bellini',
 'brokenyank',
 'buffr',
 'cadd-grc-2013',
 'CDK_PROTAC',
 'cecam-2015-julich-workshop',
 'cellfree-expression',
 'charge-datasets',
 'chiron',
 'clusterutils',
 'coddiwomple',
 'command-center',
 'conda-recipes',
 'construct-selection',
 'covid',
 'covid-moonshot',
 'covid-moonshot-manuscript',
 'cpdetect',
 'cragganmore',
 'create-rna-nucleoside-dataset',
 'cup-xiv',
 'cyp450-affinity',
 'DDR1_and_kinase_promiscuity_materials',
 'density',
 'density-measurements',
 'dispensing-errors-manuscript',
 'docker-fah-client',
 'download-qca-datasets',
 'Drylab-Protocols',
 'duke-cbb-talk-2014-10-06',
 'dunbrack_assignment',
 'enhanced-sampling-tmem175',
 'ensembler',
 'ensembler-manuscripts',
 'Ensembler2',
 'Epik-Ligands',
 'ERK-ancestral-materials',
 'erlangen-2014',
 'espaloma',
 'espaloma-0.3.0-manuscript',
 'espalomax',
 'espaloma_charge',
 'examol',
 'ExpressionExplorer',
 'fah-open-datasets',
 'fah-public-data',
 'fah-tools',
 'fah-xchem',
 'fah-xchem-notebooks',
 'fah-xchem-testdata',
 'fahmunge',
 'fahmunge-testdata',
 'fah_prep',
 'feflow',
 'ffsettings',
 'fluorescence-assay-manuscript',
 'fluorescence_assay_working_data',
 'folding_at_home_scripts',
 'fortuna',
 'fragmenter_data',
 'gbff',
 'gbff-prototypes',
 'gcmc-counterions',
 'gcncharge',
 'geometry-benchmark-espaloma',
 'gibbs',
 'gimlet',
 'gnn_charge',
 'goodiebag',
 'gpcr',
 'her2',
 'host-guest',
 'hpno',
 'hsa-affinity',
 'Human-Serum-Albumin',
 'hx',
 'iapetus',
 'iapetus-examples',
 'imatinib-itc',
 'importance-of-shadow-work',
 'infiniteswitch',
 'integrator-benchmark',
 'IR783-QSNAP',
 'itc-worksheet',
 'itctools',
 'itc_experiment_notebook',
 'jager',
 'kaizen',
 'kinalysis',
 'kinase-benchmark',
 'kinase-ecoli-expression-panel',
 'kinase-metadynamics',
 'kinase-modeller',
 'kinase-resistance-mutants',
 'kinome-data',
 'kinomeDB-webclient',
 'klogw',
 'latex-manuscript-template',
 'LDHA-MCCE',
 'ligand-binding-pathsampling',
 'Ligandr',
 'liquid-handling-tester',
 'LiquidBenchmark',
 'malt',
 'mcce-charges',
 'mcce-structures',
 'men1',
 'metk',
 'mhc',
 'mltl',
 'mmtools',
 'modelforge',
 'model_systems',
 'moldr',
 'mpiplus',
 'msm-mfpt',
 'msm-pipeline',
 'MSMs',
 'mtenn',
 'musashi',
 'mutation-analysis',
 'nano-drugbank',
 'nanoparticles',
 'ncmc',
 'neq-switching-shadow-work',
 'neutromeratio',
 'nn-endstates',
 'nsp13-models',
 'observable-tica',
 'octomore',
 'oeante',
 'onion',
 'open-data-registry',
 'openmm',
 'openmm-eds',
 'openmm-mts-benchmark',
 'openmm-terachem',
 'openmm-tests',
 'openmm-tutorials',
 'openmm-validation',
 'openmm7tutorials',
 'OpenMMEnergyComparisons',
 'openmmmcmc',
 'openmmtools',
 'openmoltools',
 'paper-microfluidics',
 'papers-and-grants',
 'PDBAnalyzer',
 'PDBAnalyzer-results',
 'pdbbind_ml',
 'PDBfinder',
 'peanut',
 'peptide-design',
 'perses',
 'perses-barnase-barstar-paper',
 'perses-orion',
 'PersesAtFoldingAtHome',
 'persesmoviemaker',
 'pimento',
 'pinot',
 'pisco',
 'pl-benchmark-espaloma-experiment',
 'PlasmidLibraryTools',
 'plipify',
 'printable-3d-parts',
 'protons',
 'protons-templates',
 'pymbar',
 'pymbar-datasets',
 'pymbar-examples',
 'pyopenmm',
 'qmlify',
 'qmmm-hydration',
 'quacpac-orion',
 'rbd-ab-contact-analysis',
 'rbd-ace2-contact-analysis',
 'refit-espaloma',
 'resptools',
 'ring-open-fep',
 'rmsd-gradients',
 'rna-bgsu-trinucleotide',
 'rna-espaloma',
 'rna_bgsu',
 'robots',
 'ROCSALT',
 'rumm',
 'sake',
 'saltswap',
 'saltswap-results',
 'SAMPL-R01',
 'sampl4',
 'sampl5-experimental-logd-data',
 'SAMPL6-Epik-Jaguar-Manuscript',
 'SAMPL6-logP-challenge-virtual-workshop',
 'sampl6-physicochemical-properties',
 'sampl6-pKa-challenge-manuscript',
 'sampl6-pKa-measurements-manuscript',
 'SAMPL6-reference-epik-calculations-old',
 'SAMPL6-Reference-pKa-Calculations',
 'SAMPL6_logP_ref_calc',
 'sams',
 'sams_dunbrack',
 'selectivity',
 'SETD8-materials',
 'simulation-health-reports',
 'single-molecule-splitting-probabilities',
 'smml',
 'software-development',
 'spectralestimation-manuscript',
 'status',
 'super-duper-guacamole',
 't4-lysozyme-l99a-fah',
 'TargetExplorer',
 'tautomer-data',
 'tech_stuff',
 'thermo-length-learning',
 'thermodynamic-trailblazing',
 'thermopyl',
 'theses_library',
 'thresholds',
 'titrato',
 'torsionfit',
 'torsionfit_examples',
 'trpzip2',
 'TrustButVerify',
 'trypsin',
 'VAMPSchNet',
 'vanilla-espaloma-experiment',
 'vvvr',
 'wetlab-protocols',
 'yank',
 'yank-benchmark',
 'yank-examples',
 'Yank-Manuscript',
 'yank-validation',
 'YankTools',
 'zincsim']

In [8]:
all_unique_counts = 0

for repo_name in all_repos:
    repo = git.get_repo(f"{org}/{repo_name}")
    contents = repo.get_views_traffic(per="week")
    last_fortnight = contents["views"][-2:]
    unique_counts = sum([x.uniques for x in last_fortnight])
    all_unique_counts += unique_counts

Request GET /repos/choderalab/Abl_kinase_N368S/traffic/views?per=week failed with 403: Forbidden

GithubException: 403 {"message": "Must have push access to repository", "documentation_url": "https://docs.github.com/rest/metrics/traffic#get-page-views"}

In [32]:
all_unique_counts

772